In [1]:
# simple hack to support import module from parent directory
import sys
sys.path.append('../src')

In [2]:
from collections import Counter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rl4llm.utils import load_from_jsonl_file

In [5]:
sample_files = [
    "../data/synthetic_coherent_dataset/qwen2.5_3b_gsm2k/run_20250319_225709/train.jsonl.gz",
]

In [6]:
samples = []
for f in sample_files:
    samples.extend(load_from_jsonl_file(f))

print(f"Total samples: {len(samples)}")

Total samples: 31200

In [7]:
# Convert samples to pandas dataframe
df_samples = pd.DataFrame(samples)

In [8]:
display(df_samples.head())

,question,ground_truth,task_type,completion,is_coherent,model_name,prompt_tokens,completion_tokens,total_tokens
0,Riku has 25 times more stickers than Kristoff....,2210,GSM,"To solve this problem, let's follow these step...",True,Qwen/Qwen2.5-3B-Instruct,173,363,536
1,Today is my birthday and I'm three times older...,9,GSM,Let's denote your current age as \( x \).\n\nA...,False,Qwen/Qwen2.5-3B-Instruct,165,1267,1432
2,Emani has $30 more money than Howard. If Emani...,135.0,GSM,Let's break down the problem step by step.\n\n...,False,Qwen/Qwen2.5-3B-Instruct,181,988,1169
3,Xavier plays football with his friends. During...,16,GSM,"To solve this problem, let's break it down ste...",True,Qwen/Qwen2.5-3B-Instruct,185,371,556
4,James splits 4 packs of stickers that have 30 ...,6,GSM,Let's break down the problem step by step:\n\n...,True,Qwen/Qwen2.5-3B-Instruct,179,337,516

In [9]:
incoherent_items = df_samples[~df_samples['is_coherent']]
print(len(incoherent_items))

12000

In [10]:
incoherent_items.sort_values(by='completion_tokens', ascending=True, inplace=True)

/tmp/ipykernel_121524/1709842143.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  incoherent_items.sort_values(by='completion_tokens', ascending=True, inplace=True)

In [15]:
display(incoherent_items.head(1000))

,question,ground_truth,task_type,completion,is_coherent,model_name,prompt_tokens,completion_tokens,total_tokens
633,"All people named Barry are nice, while only ha...",99,GSM,To determine the number of nice people in the ...,False,Qwen/Qwen2.5-3B-Instruct,227,644,871
21923,"All people named Barry are nice, while only ha...",99,GSM,"To solve this problem, let's break it down ste...",False,Qwen/Qwen2.5-3B-Instruct,227,644,871
25738,"All people named Barry are nice, while only ha...",99,GSM,To determine the total number of nice people i...,False,Qwen/Qwen2.5-3B-Instruct,227,644,871
16871,"All people named Barry are nice, while only ha...",99,GSM,"To solve this problem, let's break it down ste...",False,Qwen/Qwen2.5-3B-Instruct,227,644,871
3836,"All people named Barry are nice, while only ha...",99,GSM,Let's break down the problem step by step to f...,False,Qwen/Qwen2.5-3B-Instruct,227,644,871
...,...,...,...,...,...,...,...,...,...
10316,"A hairstylist charges $5 for a normal haircut,...",413,GSM,To determine the weekly earnings of the hairst...,False,Qwen/Qwen2.5-3B-Instruct,203,794,997
6392,Jeremy loves to play Scrabble. He once played...,8,GSM,To determine the value of the middle letter in...,False,Qwen/Qwen2.5-3B-Instruct,208,794,1002
4204,Jeremy loves to play Scrabble. He once played...,8,GSM,"To solve this problem, let's first establish w...",False,Qwen/Qwen2.5-3B-Instruct,208,794,1002
11059,"A hairstylist charges $5 for a normal haircut,...",413,GSM,To find out how much money the hairstylist ear...,False,Qwen/Qwen2.5-3B-Instruct,203,794,997
23610,Jeremy loves to play Scrabble. He once played...,8,GSM,To determine the value of the middle letter in...,False,Qwen/Qwen2.5-3B-Instruct,208,794,1002